### ISSUE TITLE
how to get dataframe all  data convert to  gonum  dense matrix ?

### ISSUE THREAD

**Issue by mullerhai** [rocketlaunchr/dataframe-go#15]
I want to use it ,but I found some problem  ,You make the property  about  SeriesInt64 values private !!!,why ? 

would you like tell how to convert  dataframe  to  gonum  dense matrix ?

and how to use  LoadFromCSV(ctx,strings.NewReader(csvStr)),which ctx ,how to define the context.Context

**Comment by pjebs** [comment]
> would you like tell how to convert dataframe to gonum dense matrix ?

Can you use SeriesFloat64 to interact with gonum?

> and how to use LoadFromCSV(ctx,strings.NewReader(csvStr)),which ctx ,how to define the context.Context

This is a Go question. Not a dataframe question. import `context` and use `context.Background()` if you are unsure.

**Comment by mullerhai** [comment]
> context.Background()

thx,you have tell me the context use ,LoadFromCSV(ctx,strings.NewReader(csvStr))

but   dataframe all data convert to gonum dense matrix also has problem 
I use dataframe.SeriesFloat64  variable to create Dataframe,like this


	var s1 *dataframe.SeriesFloat64 = dataframe.NewSeriesFloat64("day", nil, 1, 2, 3, 4, 5, 6, 7, 8)
	var s2 *dataframe.SeriesFloat64 = dataframe.NewSeriesFloat64("day3", nil, 1, 2, 3, 4, 5, 6, 7, 8)

	var dfs  *dataframe.DataFrame = dataframe.NewDataFrame(s1,s2)


,but I  dont know how to operate dataframe dfs, I check your source code 
 when you create dataframe  ,the input param tyep  is [Series Array ]!!!  dataframe.NewDataFrame(s1,s2) , 
func NewDataFrame(se ...Series) *DataFrame

but  when I want to get dataframe series  array ,
series := dfs.Series
then convert series array to  dataframe.SeriesFloat64 array , run the program tell me

【dataframe.SeriesFloat64 not implement  Series !!!!】 and Series type has not property like values() method to get []float64 array return, oh  my god ,
would you like tell me how to convert the  dataframe  to  gonum dense matrix ,please give me some example code ,thx

**Comment by mullerhai** [comment]
> > would you like tell how to convert dataframe to gonum dense matrix ?
> 
> Can you use SeriesFloat64 to interact with gonum? The float64 slice is exported for that purpose.
> 
> > and how to use LoadFromCSV(ctx,strings.NewReader(csvStr)),which ctx ,how to define the context.Context
> 
> This is a Go question. Not a dataframe question. import `context` and use `context.Background()` if you are unsure.
I write code like this 
func series_convert_floatarray( df *dataframe.DataFrame) []float64{
	series := df.Series
	arr := make([]float64,len(df.Names())*df.NRows())

	for _,data :=range  series{
		//this  has error ,data Series type can not convert to  dataframe.SeriesFloat64
		tem_arr := (dataframe.SeriesFloat64)data
	
		arr = append(arr,tem_arr.Values )
	}
	return arr
}

**Comment by pjebs** [comment]
df.Series[0].(SeriesFloat64).Values

**Comment by mullerhai** [comment]
> df.Series[0].(SeriesFloat64).Values

	dataframe.SeriesFloat64 does not implement dataframe.Series (Append method has pointer receiver)

cant use it

**Comment by pjebs** [comment]
@propersam can you check this

**Comment by pjebs** [comment]
Try above now

**Comment by mullerhai** [comment]
> Try above now

ok ,perfect solve it ,thx

**Comment by mullerhai** [comment]
I think maybe you need to add one method like this ,maybe convenient the user like me  ,these method is base on python pandas ,


func (df *dataframe.DataFrame ) get_row(row int )[]float64{
	series := df.Series
	arr := make([]float64,0)
	for _,data :=range  series{
		arr =append(arr,data.Value(row).(float64))
	}
	return arr
}

func ( df *dataframe.DataFrame) series_convert_floatarray() []float64{
	series := df.Series
	arr := make([]float64,0)
	for _,data :=range  series{
		tem_arr := data.(*dataframe.SeriesFloat64).Values
		arr = append(arr,tem_arr...)
	}
	return arr
}

func  ( df *dataframe.DataFrame) convert_dense_matrix(row ,columns){
....}

**Comment by pjebs** [comment]
Your using the package wrong. Go is not a language you can just stay using quickly.

**Comment by mullerhai** [comment]
> Your using the package wrong. Go is not a language you can just start using quickly.

I know you say ,but I has used  java  scala python c++ c# in my company project  ,first time use golang just want to use machine learning project ,I need  numpy pandas instead of  in golang ,so do that
