### ISSUE TITLE
HOw to use CSVLoadOptions ?

### ISSUE THREAD

**Issue by mullerhai** [rocketlaunchr/dataframe-go#16]
hi 
i have one csv fiile ,has four fields [USERID ,MOVIEID,RATING, TIMESTAMP) ,LoadFromCSV default load 
all fields data type are string ,I want to change it with float64  when load init ,so I create CSVLoadOptions 
var csvOp imports.CSVLoadOptions
	csvOp.DictateDataType =make(map[string]interface{})
	csvOp.DictateDataType["USERID"]= float64(0)
	csvOp.DictateDataType["MOVIEID"]=float64(0)
	csvOp.DictateDataType["RATING"]=float64(0)
	csvOp.DictateDataType["TIMESTAMP"]=float64(0)

	ratingDf, err := imports.LoadFromCSV(ctx, file,csvOp)
but has load error  ，I dont know why ，is use the CSVLoadOptions is not correct ?

**Comment by mullerhai** [comment]
csv: invalid field or comment delimiter

**Comment by mullerhai** [comment]
UserID,MovieID,Rating,Timestamp
1,1193,5,978300760
1,661,3,978302109
1,914,3,978301968
1,3408,4,978300275
1,2355,5,978824291
1,1197,3,978302268

**Comment by mullerhai** [comment]
could you give me  a example to use  imports.CSVLoadOptions

**Comment by pjebs** [comment]
That error is from csv package from standard library which is used underneath.

https://golang.org/pkg/encoding/csv/

**Comment by pjebs** [comment]
Also the column names in csv data must match in dictate data type (including case)

**Comment by pjebs** [comment]
Also provide Comma seeing to ,

**Comment by mullerhai** [comment]
could you give me example use CSVLoadOptions please ,very thx

**Comment by mullerhai** [comment]
type CSVLoadOptions struct   Comma rune  Comment rune ,
the rune type int32 ?? but // Comma is the field delimiter.
	// The default value is ',' is string

**Comment by mullerhai** [comment]
if i need rune set value ?
csvOp.Comma =","  is error

**Comment by pjebs** [comment]
Try single quotes

**Comment by mullerhai** [comment]
var csvOp imports.CSVLoadOptions
{0 0 false false map[MOVIEID:0 RATING:0 TIMESTAMP:0 USERID:0] <nil>}
fmt.Println(csvOp)

**Comment by mullerhai** [comment]
please  show me the code to run

**Comment by pjebs** [comment]
For dictate data type, your column names don't match your csv data. The case must match

**Comment by mullerhai** [comment]
see me code ,is the correct use CSVLoadOptions   style 

	var ctx = context.Background()
	file, err := os.Open(ratingPath)
	//strings.NewReader(ratingPath)
	var csvOp imports.CSVLoadOptions
	//csvOp.Comma = 0
	csvOp.DictateDataType =make(map[string]interface{})
	csvOp.DictateDataType["USERID"]= float64(0)
	csvOp.DictateDataType["MOVIEID"]=float64(0)
	csvOp.DictateDataType["RATING"]=float64(0)
	csvOp.DictateDataType["TIMESTAMP"]=float64(0)
	//csvOp.Comma =","
	fmt.Println(csvOp)
	ratingDf, err := imports.LoadFromCSV(ctx, file,csvOp)

**Comment by pjebs** [comment]
You didn't listen to anything I wrote

**Comment by mullerhai** [comment]
csvOp.DictateDataType[fieldname ] = fieldvalueInit, I just want to know the running example ,I dont know if I write the correct code style

**Comment by pjebs** [comment]
I'll write up a detailed code sample tomr

**Comment by mullerhai** [comment]
thx you much

**Comment by pjebs** [comment]
```
opts := imports.CSVLoadOptions{
	Comma: ',',
	DictateDataType: map[string]interface{}{
		"UserID": float64(0),
		"MovieID": float64(0),
	},
}
```

**Comment by mullerhai** [comment]
like you write the sample code ,
csvOp := imports.CSVLoadOptions{
		Comma: ',',
		Comment:2,
		DictateDataType: map[string]interface{}{
			"UserID": float64(0),
			"MovieID": float64(0),
			"RATING" :float64(0),
			"TIMESTAMP" :float64(0),
		},
	}
{44 2 false false map[MovieID:0 RATING:0 TIMESTAMP:0 UserID:0] <nil>}
+-----+--------+--------+--------+------------+
|     |  403   |  2154  |   1    | 976291961  |
+-----+--------+--------+--------+------------+
| 0:  |  403   |  2082  |   3    | 976306590  |
| 1:  |  403   |  1282  |   2    | 976307555  |
| 2:  |  403   |  3897  |   4    | 1004113203 |
| 3:  |  403   |  1358  |   3    | 976302338  |
+-----+--------+--------+--------+------------+
| 4X4 | STRING | STRING | STRING |   STRING   |
+-----+--------+--------+--------+------------+

we had already declear the fields data type float64, but output  data type always [STRING ],add headers all lost

**Comment by mullerhai** [comment]
all perfectly running
