### ISSUE TITLE
Support for Go modules?

### ISSUE THREAD

**Issue by typeless** [rocketlaunchr/dataframe-go#18]
Go modules makes it easier to work on multiple forked packages at the same time.
I suppose a simple `go mod init github.com/rocketlaunchr/dataframe-go` would be sufficient to have it.

If you accept the proposal, I can submit a PR later.

**Comment by pjebs** [comment]
In a week or two, I'll be adding some new features and changing the API in a few places.
Once I complete that I will tag it v1 and add go modules.

**Comment by pjebs** [comment]
I'm hesitant to add go modules yet because although it's trivial to add a v1, there are some complexities involved when creating a breaking change and going to v2. I want to be happy with the API before I create "v1" to reduce the hassles later on.

**Comment by pjebs** [comment]
done.
