### ISSUE TITLE
It shouldn't print all the rows and columns as default

### ISSUE THREAD

**Issue by vikram-rawat** [rocketlaunchr/dataframe-go#2]
Default should print only as much as console.

![image](https://user-images.githubusercontent.com/22342596/47714677-87062500-dc63-11e8-9796-628edd11e20a.png)

**Comment by rocketlaunchr-cto** [comment]
I'll eventually fix it up so it displays the first 3 and last 3 rows.
Alternatively, you can provide a PR and replicate the `String()` function in the Series structs.

**Comment by vikram-rawat** [comment]
I am not a programmer and I am just learning Golang but I will try to help you out if possible. If there is something easy you want me to do I will surely do it.

I think this library needs
1. Import from SQL
2. Import from excel
3. select columns
4. Filter Rows
5. Group By Values
6. Basic functions like sum, mean etc....

Let me know if I can help in any of these. Best of Luck!!!

**Comment by rocketlaunchr-cto** [comment]
1. 2. I won't have time to implement import from SQL or Excel any time soon. That will require assistance from others.

3. What do you mean Select columns? 
The function `NameToColumn(seriesName string)` combined with the `Series` field can be used to select columns.

4. 5. These I will work on when I figure out the best API to do so.

6. This is doable.

**Comment by bk521234** [comment]
> I think this library needs
> 
> 1. Import from SQL
> 2. Import from excel
> 3. select columns
> 4. Filter Rows
> 5. Group By Values
> 6. Basic functions like sum, mean etc....
> 

I think these sounds like great ideas!

`1.` and `2.`  could be part of a longer term project road map. 
`4.`, `5.`, and `6.` sound like great shorter term features to tackle.

can I help out anywhere @rocketlaunchr-cto ? we will have to break up large goals into manageable pieces..

**Comment by rocketlaunchr-cto** [comment]
@bk521234 How would you like to help. I can write up a document on what you can do.

**Comment by bk521234** [comment]
i'd be willing to chip in some help to add a few features. a document could be really useful. maybe a wiki page with stuff? or small-ish projects for the near term? 

I think the more functionality the package has, the more willing people will be to adopt/ use it

**Comment by vikram-rawat** [comment]
I am not a good programmer but I can help too. But I am stuck somewhere I would want you to help me too... Start a slack channel or something where we could work.

**Comment by rocketlaunchr-cto** [comment]
@vikram-rawat @bk521234 Here are some tasks:
1. For `func (df *DataFrame) NRows() int`, insert an optional bool parameter so enable/disable the read lock inside the function. The default should be to read lock.

2. Fix up the `func (df *DataFrame) String() string {` function found in dataframe_fmt.go to show only the first 3 items, then ..., then the last 3 items, similar to how the Series.String() function behaves.

They are easy changes.

**Comment by pjebs** [comment]
This has now been fixed. Print will only show max 6 rows as summary.

**Comment by rocketlaunchr-cto** [comment]
This has now been fixed. Print will only show max 6 rows as summary.
