### ISSUE TITLE
add support for parquet read/write

### ISSUE THREAD

**Issue by xtrimf** [rocketlaunchr/dataframe-go#25]
https://github.com/xitongsys/parquet-go

**Comment by pjebs** [comment]
@propersam Can you investigate this?

**Comment by pjebs** [comment]
https://github.com/rocketlaunchr-cto/tasks/issues/97

**Comment by pjebs** [comment]
@xtrimf would you like to have a go at making a PR?

**Comment by pjebs** [comment]
Expert to parquet now implemented

**Comment by pjebs** [comment]
Parquet import now implemented
