### ISSUE TITLE
sort having issue with ctx

### ISSUE THREAD

**Issue by ayanDas-isi** [rocketlaunchr/dataframe-go#29]
sks := []dataframe.SortKey{
	{Key: "sales", Desc: true},
	{Key: "day", Desc: true},
}

df.Sort(ctx, sks)

In this code you have provided in readme, ctx is not defined any where before that. I got it is coming from context but I think we need to initialize this ctx first before calling df.Sort(ctx, sks). Kindly guide me. Thanks in advance.

**Comment by pjebs** [comment]
`ctx := context.Background()`
