### ISSUE TITLE
Timeindex and Resample like pandas

### ISSUE THREAD

**Issue by SchineCompton** [rocketlaunchr/dataframe-go#31]
Hi, This is a very helpful package, I was wondering do we have plans implementing `Timeindex` for series / dataframe and implement resample just like pandas? Could be extremely useful. If no one is doing it I am happy to contribute.

**Comment by pjebs** [comment]
I've definitely wanted to implement them. Just didn't have time.
If you can build a prototype, I can get a feel for how you plan to implement it. It will probably go into the utils package and not the pandas package.

**Comment by SachinCompton** [comment]
Perfect! I'll let you know once I have a prototype.

**Comment by pjebs** [comment]
https://towardsdatascience.com/using-the-pandas-resample-function-a231144194c4

**Comment by zdevwu** [comment]
@SachinCompton how is it going with the prototype?

**Comment by pjebs** [comment]
@zdevwu do you want to have a go at this?

**Comment by mrogojanu** [comment]
Hi, just wondering if this is progressing or not.  Looking forward for an alternative to pandas  for time series manipulation.  Thanks.

**Comment by pjebs** [comment]
I'm working on a different feature at the moment.

**Comment by ShuxiangCao** [comment]
I apologize for not having written anything about it three years ago. I had a break from the pandemic but immediately caught into other obligations. I am resolving all the issues in my GitHub and stumbled upon this one. Please accept my apology. However, I may not have enough time to contribute at the moment, so I am closing the issue for now.
