### ISSUE TITLE
Can I read CSV file in batch?

### ISSUE THREAD

**Issue by n-is** [rocketlaunchr/dataframe-go#34]
I would like to know if I can read a CSV file in batches. If it is possible, how can I do it?  I looked through the docs and examples and could not find the required information. Any help would be appreciated.

Thank you.

**Comment by pjebs** [comment]
You will have to implement it yourself. You will need familiarity with the "encoding/csv" package.

You can find guidance here: https://github.com/rocketlaunchr/dataframe-go/blob/master/imports/csv.go#L70

It is actually not that difficult to do.
