### ISSUE TITLE
Please provide a way to create a Dataframe of type array/slice and export to parquet

### ISSUE THREAD

**Issue by sumanlucky05** [rocketlaunchr/dataframe-go#41]
The library is very useful and somewhat tries to imitate the pandas library of Python . It would be very beneficial if you could provide support to create a NewSeriesArray() method that would be beneficial to create a proper parquet file.

**Comment by pjebs** [comment]
What's a series array?

**Comment by pjebs** [comment]
You can already export to parquet

**Comment by pjebs** [comment]
Parquet import now implemented
