### ISSUE TITLE
Export to Parquet example

### ISSUE THREAD

**Issue by CeciliaCoelho** [rocketlaunchr/dataframe-go#51]
Can someone give me an example of how to write the code to export a dataframe to a parquet file (couldn't find one anywhere)? I have no idea how to define the writer inside the ExportToParquet.
Knowing that i have a dataframe df, i have this code inside main:

```
ctx := context.Background()
w, err := os.Create("output.parquet")
exports.ExportToParquet(ctx, writer.NewParquetFromWriter(w, df, 4))
```

Getting this error:
![image](https://user-images.githubusercontent.com/64708317/108235567-d70f9b00-713d-11eb-950d-c57c48a4cbf3.png)

Thanks again!

**Comment by pjebs** [comment]
exports.ExportToParquet(ctx, w, df)
