### ISSUE TITLE
Draw graphs from columns of dataframe

### ISSUE THREAD

**Issue by padchin** [rocketlaunchr/dataframe-go#52]
Hi! At the moment I have managed to plot a separate dataframe column by this strange method:
```
func main() {
        // all values of df are strings representing floating point numbers
        df := df, err := imports.LoadFromCSV(ctx, r, imports.CSVLoadOptions{Comma: ';'})
	s := df.Series[2] // trying to plot column 2
	series := dataframe.NewSeriesFloat64("test_name", nil, nil)

	i := s.ValuesIterator(dataframe.ValuesOptions{InitialRow: 0, Step: 1, DontReadLock: false})
	for {
		row, vals, _ := i()
		if row == nil {
			break
		}
		val, err := strconv.ParseFloat(vals.(string), 64)
		if err != nil {
			continue
		}
		series.Append(val)
	}
	Plot(series)
}

func Plot(ser *dataframe.SeriesFloat64) {
	ctx := context.TODO()
	cs, _ := wcharczuk_chart.S(ctx, ser, nil, nil)
	graph := chart.Chart{
		Title:  "test_graph",
		Width:  640,
		Height: 480,
		Series: []chart.Series{cs},
	}
	f, err := os.Create("graph.svg")
	if err != nil {
		panic(err)
	}
	defer f.Close()

	plt := bufio.NewWriter(f)
	_ = graph.Render(chart.SVG, plt)
}
```
Is there any simplier or more elegant method to do this job? And another question is if I can plot several columns on one plot? And if it is possible, how can I do this? Thanks in advance.

**Comment by pjebs** [comment]
1. Series string should have a function called ToFloat
2. You can add more series to  []chart.Series{cs}
3.

**Comment by padchin** [comment]
> 1. Series string should have a function called ToFloat

My ```s``` (type:  dataframe.Series) does not have this method

**Comment by pjebs** [comment]
https://pkg.go.dev/github.com/rocketlaunchr/dataframe-go#SeriesString.ToSeriesFloat64

**Comment by pjebs** [comment]
You also don't need to save plot to file. See readme on usage.

**Comment by padchin** [comment]
Ok, then. I understood conserning ```DictateDataType```. This is not my case as I don't know the name of columns in advance. But I cannot still understand how to extract ```SeriesString``` form dataframe's columns which have type ```Series```.

**Comment by pjebs** [comment]
you need to type assert

**Comment by padchin** [comment]
I would really appreciate it if you could share a small example. Because this construction is not correct:
```
v := df.Series[2]
v1 := dataframe.NewSeriesString("name", nil, v)
```
I cannot imagine what should I do now.

**Comment by pjebs** [comment]
https://medium.com/@rocketlaunchr.cloud/type-conversions-casting-type-assertions-fb295430e387

**Comment by padchin** [comment]
> https://pkg.go.dev/github.com/rocketlaunchr/dataframe-go#SeriesString.ToSeriesFloat64

Thanks for your assistance. Finally I was able to figure out the type assertions. But now I have a new question. What fuction should I pass to ```ToSeriesFloat64``` to make conversions?
