### ISSUE TITLE
LoadFromJSON Not Working

### ISSUE THREAD

**Issue by hamiwa** [rocketlaunchr/dataframe-go#56]
files, err := ioutil.ReadFile("device.json")
	if err != nil {
		fmt.Println(err)
	}

	var ctx = context.Background()
	df2, _ := imports.LoadFromJSON(ctx, strings.NewReader(string(files)))

	fmt.Println(df2.Table())

**Comment by pjebs** [comment]
what does your json file look like?

**Comment by pjebs** [comment]
what is the error message? You are `_` the error message.

**Comment by hamiwa** [comment]
Hi,
Please see JSON file content and error msg below:

JSON
#####
[
{
"device":"A",
"vendor":"A",
"nos":"",
"address":"A"
},
{
"device":"B",
"vendor":"B",
"nos":"B",
"address":"B"
}
]
error
####
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x52a54f]

goroutine 1 [running]:
github.com/rocketlaunchr/dataframe-go.(*DataFrame).Table(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        C:/Users/BLADE RUNNER/go/pkg/mod/github.com/rocketlaunchr/dataframe-go@v0.0.0-20210422123815-aaa951b82e1b/dataframe_fmt.go:38 +0x4f
main.main()
        C:/Projects/Go/src/projects/data1.go:19 +0x10f
exit status 2

**Comment by pjebs** [comment]
Currently it only supports jsonl format: https://jsonlines.org/

Let me adjust the code on a few days for your use case.

**Comment by pjebs** [comment]
In the mean time, remove the outer array and then make each object into a new line (no comma)

**Comment by hamiwa** [comment]
> In the mean time, remove the outer array and then make each object into a new line (no comma)

Thanks, I will attempt using the above method and see how this performs - Appreciate the time taken on this.

**Comment by pjebs** [comment]
Almost complete

**Comment by pjebs** [comment]
Complete. Now it supports loading from JSON arrays, JSONL arrays and JSONL objects.
It is also faster at importing.

**Comment by hamiwa** [comment]
Excellent! I will do some tests and confirm, appreciated.
