### ISSUE TITLE
Problem getting the package

### ISSUE THREAD

**Issue by Patrikios** [rocketlaunchr/dataframe-go#58]
Problem getting the package:

```
$ go get -u github.com/rocketlaunchr/dataframe-go
go get: github.com/rocketlaunchr/dataframe-go@none updating to
        github.com/rocketlaunchr/dataframe-go@v0.0.0-20211025052708-a1030444159b requires
        github.com/blend/go-sdk@v1.1.1: reading github.com/blend/go-sdk/go.mod at revision v1.1.1: unknown revision v1.1.1
```

**Comment by pjebs** [comment]
Can you use godepgraph repo to find out what is importing blend/go-sdk? Go.mod days indirect import.

I've never seen it before.

**Comment by Patrikios** [comment]
It seems it was problem caused by `dnf install` go installation on a freshly installed fedora 35 workstation. Reinstalled with the official go version. Now `dataframe-go` package is being found. Sorry for the inconvenience.

**Comment by pjebs** [comment]
I did recently change minimum version to go1.15. Could that have been why?

**Comment by Patrikios** [comment]
The default `dnf` go version is currently 1.16, hence the minimum version requirement was not the issue I believe. Most probably the 1% error in this case.
